default_platform(:ios)

before_all do
  xcversion(version: "~> 13.0")
  clear_derived_data
end

SIMULATORS = [
  'iPhone 8'
]

platform :ios do
  desc "Runs the unit tests of FootballGather"
  lane :ut do
    scan(
      scheme: "FootballGather-CI",
      clean: true,
      reset_simulator: true
    )
  end

  desc "Runs the UI tests of FootballGather"
  lane :ui do
    scan(
      scheme: "UITests",
      clean: true,
      reset_simulator: true,
      devices: SIMULATORS
    )
  end

  desc "Takes screenshots"
  lane :screenshots do
    capture_ios_screenshots(
      clear_previous_screenshots: true
    )

    capture_ios_screenshots(
      dark_mode: true
    )
  end

  desc "Distributes IPA to AppStore"
  lane :distribute_release_app do
    setup_ci
    connect_to_appstore
    sync_device_info
    sync_certs(type: "appstore")
    bump_versions
    build_release_app
    upload_app_to_testflight
  end

  private_lane :connect_to_appstore do
    app_store_connect_api_key(
      duration: 200,
      is_key_content_base64: true,
      in_house: false
    )
  end

  private_lane :sync_device_info do
    register_devices(
      devices_file: "fastlane/Devicefile"
    )
  end

  private_lane :sync_certs do |options|
    selectedType = options[:type]
    match(
      type: selectedType,
      force_for_new_devices: true,
      readonly: true
    )
  end

  private_lane :bump_versions do
    version_number = sh("git describe --tags $(git rev-list --tags --max-count=1) | tr -d '\n'")
    increment_build_number
    increment_version_number(
      version_number: version_number
    )
  end

  private_lane :build_release_app do
    gym(
      scheme: "FootballGather",
      clean: true,
      output_directory: "./build-store",
      export_method: "app-store"
    )
  end

  private_lane :upload_app_to_testflight do
    pilot(
      distribute_external: false,
      notify_external_testers: false,
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )
  end

end
