default_platform(:ios)

before_all do
  xcversion(version: "~> 13.0")
  clear_derived_data
end

SIMULATORS = [
  'iPhone 8'
]

platform :ios do
  desc "Runs the unit tests of FootballGather"
  lane :ut do
    scan(
      scheme: "FootballGather-CI",
      clean: true,
      reset_simulator: true
    )
  end

  desc "Runs the UI tests of FootballGather"
  lane :ui do
    scan(
      scheme: "UITests",
      clean: true,
      reset_simulator: true,
      devices: SIMULATORS
    )
  end

  desc "Take screenshots"
  lane :screenshots do
    capture_ios_screenshots(
      clear_previous_screenshots: true
    )

    capture_ios_screenshots(
      dark_mode: true
    )
  end

end
