devices([
  "iPhone 8",
  "iPhone 13 Pro Max",
  "iPhone 11 Pro",
  "iPhone 8 Plus"
  "iPad Pro (9.7-inch)",
  "iPad Pro (11-inch) (3rd generation)",
  "iPad Pro (12.9-inch) (5th generation)"
])

languages([
  "en-US"
])

scheme("Snapshots")
output_directory("./screenshots")
clean(true)
erase_simulator(true)
stop_after_first_error(true)
concurrent_simulators(true)
skip_open_summary(true)
skip_helper_version_check(true)
override_status_bar(true)
