devices([
  "iPhone 15",
  "iPhone 15 Pro Max",
  "iPhone 15 Pro",
  "iPhone 15 Plus",
  "iPad (10th generation)",
  "iPad Pro 11-inch (M4)",
  "iPad Pro 13-inch (M4)"
])

languages([
  "en-US"
])

scheme("Snapshots")
output_directory("./screenshots")
clean(true)
erase_simulator(true)
stop_after_first_error(true)
concurrent_simulators(true)
skip_open_summary(true)
skip_helper_version_check(true)
override_status_bar(true)
