name: Development Workflow

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: macos-15
    defaults:
      run:
        working-directory: ./FootballGather
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/FootballGather/Gemfile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - run: bundle install
      
      - name: Select Xcode
        run: |
          ls /Applications | grep Xcode
          sudo xcode-select -switch /Applications/Xcode_16.1.app

      - name: Run UT
        run: bundle exec fastlane ut
